/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  // prefix: "b3-react-",
  // important: ".b3-root",
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    screens: {
      "3xl": { max: "1579px" },
      // => @media (max-width: 1579px) { ... }
      "2xl": { max: "1419px" },
      // => @media (max-width: 1419px) { ... }
      xl: { max: "1259px" },
      // => @media (max-width: 1259px) { ... }
      lg: { max: "1023px" },
      // => @media (max-width: 1023px) { ... }
      md: { max: "767px" },
      // => @media (max-width: 767px) { ... }
      sm: { max: "480px" },
      // => @media (max-width: 480px) { ... }
    },
    extend: {
      fontFamily: {
        "neue-montreal-bold": ['"Neue Montreal Bold"', "sans-serif"],
        "neue-montreal": ['"Neue Montreal Regular"', "sans-serif"],
        "neue-montreal-book": ['"Neue Montreal Book"', "sans-serif"],
        "neue-montreal-medium": ['"Neue Montreal Medium"', "sans-serif"],
        "neue-montreal-semibold": ['"Neue Montreal Semibold"', "sans-serif"],
        "calibre-bold": ['"Calibre Bold"', "sans-serif"],
        "calibre-heavy": ['"Calibre Heavy"', "sans-serif"],
        calibre: ['"Calibre Regular"', "sans-serif"],
        pack: ["Pack", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        "b3-react-background": "hsl(var(--b3-react-background))",
        "b3-react-foreground": "hsl(var(--b3-react-foreground))",
        "b3-react-card": "hsl(var(--b3-react-card))",
        "b3-react-card-foreground": "hsl(var(--b3-react-card-foreground))",
        "b3-react-subtle": "hsl(var(--b3-react-subtle))",
        "b3-react-secondary-foreground": "hsl(var(--b3-react-secondary-foreground))",
        "b3-react-primary": "hsl(var(--b3-react-primary))",
        "b3-react-primary-foreground": "hsl(var(--b3-react-primary-foreground))",
        "b3-react-muted-foreground": "hsl(var(--b3-react-muted-foreground))",
        "b3-react-border": "hsl(var(--b3-react-border))",
        "b3-react-muted": "hsl(var(--b3-react-muted))",
        "b3-react-popover": "hsl(var(--b3-react-popover))",
        "b3-react-ring": "hsl(var(--b3-react-ring))",
        "b3-react-popover": "hsl(var(--b3-react-popover))",
        "b3-react-popover-foreground": "hsl(var(--b3-react-popover-foreground))",

        "b3-foreground-muted": "hsl(var(--b3-foreground-muted))",
        "b3-primary-blue": "hsl(var(--b3-primary-blue))",
        "b3-primary-wash": "hsl(var(--b3-primary-wash))",
        "b3-grey": "hsl(var(--b3-grey))",
        "b3-line": "hsl(var(--b3-line))",
        "b3-white": "hsl(var(--b3-white))",
        "b3-background": "hsl(var(--b3-background))",
        "b3-positive": "hsl(var(--b3-positive))",
        "b3-negative": "hsl(var(--b3-negative))",

        // Anyspend, we get this from apps/anyspend-web/tailwind.config.ts
        "as-primary": "hsl(var(--as-primary))",
        "as-content-primary": "hsl(var(--as-text-primary))",
        "as-content-secondary": "hsl(var(--as-content-secondary))",
        "as-surface-primary": "hsl(var(--as-surface-primary))",
        "as-surface-secondary": "hsl(var(--as-surface-secondary))",
        "as-border-primary": "hsl(var(--as-border-primary))",
        "as-border-secondary": "hsl(var(--as-border-secondary))",
        "as-on-surface-1": "hsl(var(--as-on-surface-1))",
        "as-on-surface-2": "hsl(var(--as-on-surface-2))",
        "as-on-surface-3": "hsl(var(--as-on-surface-3))",
        "as-on-surface-4": "hsl(var(--as-on-surface-4))",
        "as-stroke": "hsl(var(--as-stroke))",
        "as-n-8": "hsl(var(--as-n-8))",
        "as-brand": "hsl(var(--as-brand))",
        "as-light-brand": "hsl(var(--as-light-brand))",
        "as-yellow": "hsl(var(--as-yellow))",
        "as-secondary": "hsl(var(--as-secondary))",
        "as-red": "hsl(var(--as-red))",
        "as-error-secondary": "hsl(var(--as-error-secondary))",
        "as-content-icon-error": "hsl(var(--as-content-icon-error))",
        "as-on-surface-disabled": "hsl(var(--as-on-surface-disabled))",
        "as-on-disabled": "hsl(var(--as-on-disabled))",
        "as-quaternary": "hsl(var(--as-quaternary))",
        "as-tertiarry": "hsl(var(--as-tertiarry))",
        "as-success-secondary": "hsl(var(--as-success-secondary))",
        "as-content-icon-success": "hsl(var(--as-content-icon-success))",
        "as-content-disabled": "hsl(var(--as-content-disabled))",

        "warning-50": "var(--warning-50)",
        "warning-200": "var(--warning-200)",
        "warning-700": "var(--warning-700)",
        "error-50": "var(--error-50)",
        "error-200": "var(--error-200)",
        "error-700": "var(--error-700)",
        "brand-50": "var(--brand-50)",
        "brand-200": "var(--brand-200)",
        "brand-700": "var(--brand-700)",
        "brand-tertiary": "var(--brand-tertiary)",
        "success-50": "var(--success-50)",
        "success-200": "var(--success-200)",
        "success-700": "var(--success-700)",
        "fg-quaternary": "var(--fg-quaternary)",
        "content-primary": "var(--content-primary)",
        "content-secondary": "var(--content-secondary)",
        "content-placeholder": "var(--content-placeholder)",
        "on-surface-primary-alt": "var(--on-surface-primary-alt)",
        "on-surface-btn": "var(--on-surface-btn)",
      },
      keyframes: {
        "pulse-fade": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "pulse-fade": "pulse-fade 1.5s ease-in-out infinite",
      },
    },
  },
  corePlugins: {
    // Enable nesting support
    preflight: true,
  },
  plugins: [require("tailwindcss-animate")],
};
