name: Build Global Accounts Documentation

on:
  push:
    branches: [main]
    paths:
      - "apps/global-accounts/**"
      - "packages/sdk/**"
  pull_request:
    branches: [main]
    paths:
      - "apps/global-accounts/**"
      - "packages/sdk/**"
  workflow_dispatch:
env:
  NODE_OPTIONS: --max_old_space_size=8192
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @b3dotfun/sdk package
        run: pnpm --filter @b3dotfun/sdk build

      - name: Build documentation app
        run: pnpm --filter global-accounts build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: global-accounts-docs-dist
          path: apps/global-accounts/dist/
          retention-days: 7
